spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/delivery
    username: sergei
    password: 12345

logging:
  level:
    "ru.yandex.practicum": TRACE
    "org.springframework.orm.jpa": INFO
    "org.springframework.transaction": INFO
    "org.springframework.transaction.interceptor": TRACE
    "org.springframework.orm.jpa.JpaTransactionManager": DEBUG
    "org.hibernate.SQL": DEBUG
    "org.hibernate.orm.jdbc.bind": trace

server:
  port: 0

delivery:
  base_cost: 5.0
  coefficient_for_warehouse_address_1: 1
  coefficient_for_warehouse_address_2: 2
  coefficient_for_fragility: 0.2
  coefficient_for_weight: 0.3
  coefficient_for_volume: 0.2
  delivery_street_coefficient_does_not_match_warehouse_address: 0.2