services:
  store-db:
    image: postgres:16.1
    container_name: commerce-db
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=sergei
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10