spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show_sql: false
  sql:
    init:
      mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:6432/smart-home
    username: sergei
    password: 12345

  kafka:
    consumer:
      hub:
        bootstrap-servers: localhost:9092
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: ru.yandex.practicum.kafka.deserializer.HubEventDeserializer
        group-id: hubEvent
        client-id: hub-event-consumer
        auto-offset-reset: earliest
        enable-auto-commit: false
      snapshots:
        bootstrap-servers: localhost:9092
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: ru.yandex.practicum.kafka.deserializer.SnapshotDeserializer
        group-id: snapshot
        client-id: snapshots-consumer
        auto-offset-reset: earliest
        enable-auto-commit: false

server:
  port: 8083

analyzer:
  topic:
    snapshots-topic: telemetry.snapshots.v1
    hub-event-topic: telemetry.hubs.v1

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
logging:
  level:
    org.springframework.kafka: INFO
    ru.yandex.practicum: TRACE